import { Dimensions, StyleSheet } from "react-native";
import { fonts } from "./constants";

const { width, height } = Dimensions.get("window");
const vw = (percent: number) => (width * percent) / 100;
const vh = (percent: number) => (height * percent) / 100;
const token = {
	saveBtn:      "#1E3A5F",
	textNavy:     "#3D5A80",
	textMuted:    "#7A95AD",
	borderMuted:  "#A8BDD0",
	cardBg:       "#FFFFFF",
	surfaceGrey:  "#EEF2F7",
	textOnBg:     "#FFFFFF",
	textOnBgSub:  "rgba(255,255,255,0.78)",
	textName:     "#1E3A5F",
	textEmail:    "#7A95AD",
	textBio:      "#3D5A80",
	noticeBg:     "#EEF2F7",
	noticeBorder: "#A8BDD0",
	noticeText:   "#3D5A80",
	linkCardBg:   "#EEF2F7",
	linkCardBorder:"#A8BDD0",
	linkLabel:    "#3D5A80",
	linkUrl:      "#3B82F6",
	primaryBtn:      "#1E3A5F",
	primaryBtnText:  "#FFFFFF",
	logoutBtn:       "#FEE2E2",
	logoutBtnBorder: "#fecaca",
	logoutBtnText:   "#B91C1C",
	avatarBorder:    "#FFFFFF",
	avatarInnerRing: "#A8BDD0",
	radiusMd:   12,
	radiusLg:   24,
	radiusPill: 999,
	sectionGap: 20,
};
const AVATAR_SIZE   = vw(28);
const AVATAR_RADIUS = AVATAR_SIZE / 2;
const CARD_TOP      = vh(33);
const AVATAR_TOP    = CARD_TOP - AVATAR_RADIUS;

export { AVATAR_SIZE, AVATAR_TOP, CARD_TOP };

export const ProfilePageStyling = StyleSheet.create({
	background: {
		flex: 1,
		width: "100%",
		height: "100%",
	},
	safe: {
		flex: 1,
	},
	header: {
		position: "absolute",
		top: vh(9),
		left: vw(6),
		right: vw(6),
		
	},
	pageTitle: {
		fontSize: vw(9),
		fontWeight: "800",
		letterSpacing: 0.3,
		color: token.textOnBg,
	},
	subtitle: {
		marginTop: 5,
		fontSize: vw(4),
		color: token.textOnBgSub,
		letterSpacing: 0.2,
	},
	container: {
		position: "absolute",
		top: CARD_TOP,
		left: 0,
		right: 0,
		bottom: 0,
		backgroundColor: token.cardBg,
		borderTopLeftRadius: token.radiusLg,
		borderTopRightRadius: token.radiusLg,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: -4 },
		shadowOpacity: 0.07,
		shadowRadius: 10,
		elevation: 8,
	},
	scrollContent: {
		alignItems: "center",
		paddingTop: AVATAR_RADIUS + 14, 
		paddingHorizontal: vw(6),
		paddingBottom: 48,
	},
	avatarWrapper: {
		position: "absolute",
		top: AVATAR_TOP,
		alignSelf: "center",
		left: (width - AVATAR_SIZE) / 2, 
		width: AVATAR_SIZE,
		height: AVATAR_SIZE,
		zIndex: 10,
	},
	avatar: {
		width: AVATAR_SIZE,
		height: AVATAR_SIZE,
		borderRadius: AVATAR_RADIUS,
		borderWidth: 4,
		borderColor: token.avatarBorder,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.15,
		shadowRadius: 10,
		elevation: 8,
	},
	userName: {
		fontSize: vw(6),
		fontWeight: "800",
		color: token.textName,
		textAlign: "center",
		fontFamily: fonts.body,
		letterSpacing: 0.2,
		marginBottom: 4,
	},
	subtitleText: {
		fontSize: vw(3.5),
		color: token.textEmail,
		textAlign: "center",
		fontFamily: fonts.body,
		marginBottom: 6,
	},
	bioText: {
		fontSize: vw(3.8),
		color: token.textBio,
		textAlign: "center",
		fontFamily: fonts.body,
		lineHeight: vw(5.5),
		marginBottom: 10,
		paddingHorizontal: vw(4),
	},
	emptyText: {
		fontSize: 13,
		color: token.textMuted,
		marginTop: 10,
		textAlign: "center",
		fontFamily: fonts.body,
		fontStyle: "italic",
	},
	notice: {
		marginTop: 10,
		marginBottom: 4,
		fontSize: vw(3.3),
		color: token.noticeText,
		letterSpacing: 0.2,
		textAlign: "center",
		paddingHorizontal: vw(4),
		paddingVertical: 10,
		backgroundColor: token.noticeBg,
		borderWidth: 1,
		borderColor: token.noticeBorder,
		borderRadius: token.radiusMd,
		width: "100%",
		fontFamily: fonts.body,
		overflow: "hidden",
	},
	linkContainer: {
		width: "100%",
		paddingVertical: 12,
		paddingHorizontal: 16,
		marginBottom: 8,
		backgroundColor: token.linkCardBg,
		borderRadius: token.radiusMd,
		borderWidth: 1.5,
		borderColor: token.linkCardBorder,
	},
	linkLabel: {
		fontSize: 11,
		fontWeight: "700",
		color: token.linkLabel,
		fontFamily: fonts.body,
		letterSpacing: 0.8,
		textTransform: "uppercase",
		marginBottom: 2,
	},
	linkUrl: {
		fontSize: 14,
		color: token.linkUrl,
		fontFamily: fonts.body,
		textDecorationLine: "underline",
	},
	editButton: {
		marginTop: token.sectionGap,
		backgroundColor: token.primaryBtn,
		paddingVertical: 15,
		paddingHorizontal: vw(14),
		borderRadius: token.radiusPill,
		alignItems: "center",
		width: "100%",
		shadowColor: token.primaryBtn,
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.25,
		shadowRadius: 10,
		elevation: 5,
	},
	logoutButton: {
		marginTop: 10,
		backgroundColor: token.logoutBtn,
		paddingVertical: 14,
		paddingHorizontal: vw(14),
		borderRadius: token.radiusPill,
		alignItems: "center",
		width: "100%",
		borderWidth: 1,
		borderColor: token.logoutBtnBorder,
	},
	buttonText: {
		fontWeight: "700",
		fontFamily: fonts.body,
		fontSize: 15,
		letterSpacing: 0.4,
		color: token.primaryBtnText,
	},

	// kept for backward compat (guest notice reuses this)
	title: {
		fontSize: vw(5.5),
		fontWeight: "700",
		color: token.textName,
		marginBottom: 4,
		textAlign: "center",
		fontFamily: fonts.body,
	},
});