import { Dimensions, StyleSheet } from "react-native";
import { colors, fonts } from "../../src/styling/constants";

const { width, height } = Dimensions.get("window");
export const vw = (p: number) => (width * p) / 100;
const vh = (p: number) => (height * p) / 100;

export const UpdateProfileStyling = StyleSheet.create({
	background: {
		flex: 1,
		width: "100%",
		height: "100%",
	},
	safe: {
		flex: 1,
		flexDirection: "column",
		alignItems: "center",
	},
	header: {
		height: vh(7),
		justifyContent: "center",
		alignItems: "center",
	},
	pageTitle: {
		fontSize: vw(8),
		fontWeight: "900",
		letterSpacing: 3,
		color: "#A8C8E8",
		textAlign: "center",
	},
	subtitle: {
		marginTop: 6,
		fontSize: vw(4),
		color: "#ffffff",
		opacity: 0.9,
		letterSpacing: 1,
		textAlign: "center",
	},
	container: {
		position: "absolute",
		top: vh(15),
		width: "100%",
		bottom: 0,
		backgroundColor: colors.lightGrey,
		borderTopLeftRadius: 8,
		borderTopRightRadius: 8,
		padding: 20,
	},
	label: {
		fontFamily: fonts.body,
		fontWeight: "600",
		marginTop: 12,
		marginBottom: 4,
		color: colors.darkNavy,
		fontSize: 14,
	},
	input: {
		borderWidth: 1,
		borderColor: colors.lightGrey2,
		color: colors.darkNavy,
		backgroundColor: colors.white,
		borderRadius: 8,
		padding: 10,
		fontFamily: fonts.body,
		fontSize: 14,
		margin: 2,
	},
	inputInfo: {
		textAlign: "center",
		color: colors.lightGrey2,
		fontStyle: "italic",
		fontFamily: fonts.body,
		fontSize: 12,
		marginTop: 4,
	},
	avatarPreview: {
		width: vw(20),
		height: vw(20),
		borderRadius: vw(10),
		alignSelf: "center",
		marginVertical: 10,
		borderWidth: 2,
		borderColor: colors.darkNavy,
	},
	avatarPlaceholder: {
		width: vw(20),
		height: vw(20),
		borderRadius: vw(10),
		alignSelf: "center",
		marginVertical: 10,
		backgroundColor: colors.lightGrey2,
		justifyContent: "center",
		alignItems: "center",
	},
	avatarPlaceholderText: {
		fontSize: 10,
		color: colors.white,
		textAlign: "center",
		fontFamily: fonts.body,
	},
	avatarGrid: {
		flexDirection: "row",
		flexWrap: "wrap",
		justifyContent: "space-between",
		marginTop: 8,
		gap: 8,
	},
	avatarOption: {
		width: "30%",
		aspectRatio: 1,
		borderRadius: 2,
		borderWidth: 2,
		borderColor: "transparent",
	},
	avatarOptionSelected: {
		borderColor: colors.darkNavy,
		transform: [{ scale: 1.05 }],
	},
	avatarOptionImage: {
		width: "100%",
		height: "100%",
	},
	linkContainer: {
		marginBottom: 10,
		backgroundColor: colors.white,
		padding: 10,
		borderRadius: 8,
		borderWidth: 1,
		borderColor: colors.lightGrey2,
	},
	addButton: {
		backgroundColor: colors.darkBlue,
		padding: 12,
		borderRadius: 8,
		alignItems: "center",
		marginTop: 10,
	},
	saveButton: {
		backgroundColor: colors.darkNavy,
		padding: 14,
		borderRadius: 8,
		alignItems: "center",
		marginTop: 20,
	},
	cancelButton: {
		backgroundColor: colors.lightGrey2,
		padding: 14,
		borderRadius: 8,
		alignItems: "center",
		marginTop: 10,
	},
	removeButton: {
		backgroundColor: "#d32f2f",
		padding: 10,
		borderRadius: 6,
		alignItems: "center",
		marginTop: 5,
	},
	buttonText: {
		color: colors.white,
		fontWeight: "700",
		fontFamily: fonts.body,
		fontSize: 16,
	},
});
