import { Dimensions, StyleSheet } from "react-native";
import { fonts } from "../../src/styling/constants";

const { width, height } = Dimensions.get("window");
export const vw = (p: number) => (width * p) / 100;
const vh = (p: number) => (height * p) / 100;
// color tokens to be used 
const token = {
	glassBorder: "rgba(255,255,255,0.35)",
	cardBg: "#FFFFFF",
	cardBorder: "#E2E6ED",
	textPrimary: "#FFFFFF",       
	textOnCard: "#1E3A5F",        
	textSecondary: "rgba(255,255,255,0.75)",
	textMuted: "#1E3A5F",
	textLabel: "#374151",
	inputBorder: "#9CA3AF",
	inputBg: "#FFFFFF",
	inputText: "#374151",
	inputPlaceholder: "#9CA3AF",
	saveBtn: "#1E3A5F",           
	saveBtnText: "#FFFFFF",
	addBtn: "#3B82F6",            
	cancelBtn: "#fecaca",
	cancelBtnBorder: "#E2E6ED",
	cancelBtnText: "#000000aa",
	dangerBtn: "#fa3838",
	dangerBtnBorder: "#FECACA",
	dangerBtnText: "#B91C1C",
	avatarRing: "#3B82F6",
	avatarRingSelected: "#1E3A5F",
	badgeBg: "rgba(0,0,0,0.45)",
	pickerBg: "#F7F8FA",
	pickerBorder: "#E2E6ED",
	radiusSm: 10,
	radiusMd: 12,
	radiusLg: 20,
	radiusPill: 999,
	sectionGap: 22,
	gap: 8,
};

export const UpdateProfileStyling = StyleSheet.create({
	background: {
		flex: 1,
		width: "100%",
		height: "100%",
	},
	safe: {
		flex: 1,
		flexDirection: "column",
		alignItems: "center",
	},
	header: {
		height: vh(11),
		justifyContent: "flex-end",
		alignItems: "flex-start",
		paddingHorizontal: vw(6),
		paddingBottom: 14,
		width: "100%",
	},
	pageTitle: {
		fontSize: vw(8),
		fontWeight: "800",
		letterSpacing: 0.3,
		color: token.textPrimary,
		textAlign: "left",
	},
	subtitle: {
		marginTop: 4,
		fontSize: vw(3.5),
		color: token.textSecondary,
		letterSpacing: 0.3,
		textAlign: "left",
	},
	container: {
		position: "absolute",
		top: vh(20),
		width: "100%",
		bottom: 0,
		backgroundColor: token.cardBg,
		borderTopLeftRadius: token.radiusLg,
		borderTopRightRadius: token.radiusLg,
		paddingHorizontal: vw(5),
		paddingTop: 24,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: -3 },
		shadowOpacity: 0.06,
		shadowRadius: 8,
		elevation: 6,
	},
	label: {
		fontFamily: fonts.body,
		fontWeight: "600",
		marginTop: token.sectionGap,
		marginBottom: 6,
		color: token.textLabel,
		fontSize: 12,
		letterSpacing: 0.8,
		textTransform: "uppercase",
	},
	input: {
		borderWidth: 1.5,
		borderColor: token.inputBorder,
		color: token.inputText,
		backgroundColor: token.inputBg,
		borderRadius: token.radiusMd,
		paddingVertical: 11,
		paddingHorizontal: 14,
		fontFamily: fonts.body,
		fontSize: 15,
		marginVertical: 4,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.03,
		shadowRadius: 2,
		elevation: 1,
	},
	inputInfo: {
		color: token.textMuted,
		fontStyle: "italic",
		fontFamily: fonts.body,
		fontSize: 11.5,
		marginTop: 4,
		textAlign: "center",
	},
	avatarPreviewWrapper: {
		alignSelf: "center",
		marginVertical: 16,
		position: "relative",
	},
	avatarPreview: {
		width: vw(26),
		height: vw(26),
		borderRadius: vw(13),
		borderWidth: 3,
		borderColor: token.avatarRing,
		shadowColor: token.avatarRing,
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.25,
		shadowRadius: 10,
		elevation: 6,
	},
	avatarEditBadge: {
		position: "absolute",
		bottom: 2,
		right: 2,
		width: vw(7),
		height: vw(7),
		borderRadius: vw(3.5),
		backgroundColor: token.badgeBg,
		borderWidth: 1.5,
		borderColor: "rgba(255,255,255,0.7)",
		justifyContent: "center",
		alignItems: "center",
	},
	avatarEditBadgeText: {
		color: "#FFFFFF",
		fontSize: vw(3.5),
		lineHeight: vw(4),
	},
	avatarPlaceholder: {
		width: vw(26),
		height: vw(26),
		borderRadius: vw(13),
		backgroundColor: "#F3F4F6",
		justifyContent: "center",
		alignItems: "center",
		borderWidth: 2,
		borderColor: token.inputBorder,
	},
	avatarPlaceholderText: {
		fontSize: 11,
		color: token.textMuted,
		textAlign: "center",
		fontFamily: fonts.body,
	},
	avatarPickerContainer: {
		marginTop: 12,
		backgroundColor: token.pickerBg,
		borderRadius: token.radiusMd,
		borderWidth: 1.5,
		borderColor: token.pickerBorder,
		padding: 14,
	},
	avatarPickerLabel: {
		color: token.textMuted,
		fontSize: 11,
		letterSpacing: 0.8,
		textTransform: "uppercase",
		fontFamily: fonts.body,
		marginBottom: 10,
		textAlign: "center",
	},
	avatarGrid: {
		flexDirection: "row",
		flexWrap: "wrap",
		justifyContent: "flex-start",
		gap: token.gap,
	},
	avatarOption: {
		width: "30%",
		aspectRatio: 1,
		borderRadius: token.radiusMd,
		borderWidth: 2,
		borderColor: "transparent",
		overflow: "hidden",
	},
	avatarOptionSelected: {
		borderColor: token.avatarRingSelected,
	},
	avatarOptionImage: {
		width: "100%",
		height: "100%",
	},
	linkContainer: {
		marginBottom: 10,
		backgroundColor: "#F7F8FA",
		padding: 14,
		borderRadius: token.radiusMd,
		borderWidth: 1.5,
		borderColor: token.cardBorder,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.03,
		shadowRadius: 2,
		elevation: 1,
	},
	addButton: {
		backgroundColor: token.addBtn,
		paddingVertical: 13,
		paddingHorizontal: 20,
		borderRadius: token.radiusPill,
		alignItems: "center",
		marginTop: 16,
	},
	saveButton: {
		backgroundColor: token.saveBtn,
		paddingVertical: 15,
		paddingHorizontal: 20,
		borderRadius: token.radiusPill,
		alignItems: "center",
		marginTop: token.sectionGap,
		shadowColor: token.saveBtn,
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.25,
		shadowRadius: 10,
		elevation: 5,
	},
	cancelButton: {
		backgroundColor: token.cancelBtn,
		paddingVertical: 14,
		paddingHorizontal: 20,
		borderRadius: token.radiusPill,
		alignItems: "center",
		marginTop: 10,
		borderWidth: 1,
		borderColor: token.cancelBtnBorder,
	},
	removeButton: {
		backgroundColor: token.dangerBtn,
		paddingVertical: 10,
		paddingHorizontal: 14,
		borderRadius: token.radiusSm,
		alignItems: "center",
		marginTop: 6,
		borderWidth: 1,
		borderColor: token.dangerBtnBorder,
	},
	buttonText: {
		color: token.saveBtnText,
		fontWeight: "700",
		fontFamily: fonts.body,
		fontSize: 15,
		letterSpacing: 0.4,
	},
});