name: Build and Deploy Frontend

on:
  push:
    branches: [main]
    paths:
      - 'shatter-web/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: shatter-web 

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Test success
        run: echo "Frontend build succeeded"
